version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    ports: ["5433:5432"]
    volumes:
      - ./infra/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    ports: ["6379:6379"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]

  gateway-api:
    build:
      context: ./backend
      dockerfile: services/gateway-api/Dockerfile
    ports: ["8088:8080"]

  auth-service:
    build:
      context: ./backend
      dockerfile: services/auth-service/Dockerfile
  user-service:
    build:
      context: ./backend
      dockerfile: services/user-service/Dockerfile
  chat-service:
    build:
      context: ./backend
      dockerfile: services/chat-service/Dockerfile
  group-service:
    build:
      context: ./backend
      dockerfile: services/group-service/Dockerfile
  media-service:
    build:
      context: ./backend
      dockerfile: services/media-service/Dockerfile
    environment:
      S3__AccessKey: minio
      S3__SecretKey: minio123
      S3__Endpoint: http://minio:9000
      S3__PublicUrl: http://localhost:9000
  call-service:
    build:
      context: ./backend
      dockerfile: services/call-service/Dockerfile
  notification-service:
    build:
      context: ./backend
      dockerfile: services/notification-service/Dockerfile
  presence-service:
    build:
      context: ./backend
      dockerfile: services/presence-service/Dockerfile

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports: ["5173:5173"]
